#!/bin/bash

docker kill chef-server-standalone || true
docker rm chef-server-standalone || true

# run in background
# docker run --privileged --name chef-server-standalone -v ~/chef-server-logs:/var/log -p 443:443 -d  chef-server-standalone

# run in foreground
docker run --privileged --name chef-server-standalone \
  -v ~/chef-server-opt:/var/opt \
  -v ~/chef-server-logs:/var/log \
  -p 443:443 -ti chef-server-standalone
