#!/bin/bash

docker stop chef-server-standalone || true
docker rm chef-server-standalone || true

. $(dirname "$0")/variables.sh

# run in background
# docker run --privileged --name chef-server-standalone \
#   -v ~/chef-server-opt:/var/opt \
#   -p 443:443 -d chef-server-standalone

# run in foreground
docker run --privileged --name chef-server-standalone \
  -v ~/chef-server-opt:/var/opt \
  -p 443:443 -ti chef-server-standalone
